services:
  app-backend:
    build: .
    container_name: gpiv_backend_container
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-neon}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8090
