server.port=${SERVER_PORT:8090}

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-shy-math-ac52y9a5-pooler.sa-east-1.aws.neon.tech/AST-GPIV-DB?user=neondb_owner&password=npg_XhHCN3O0Vjyt&sslmode=require&channelBinding=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_XhHCN3O0Vjyt}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USER:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:false}
app.api.usuarios.semilla.admin.clave=${SEED_ADMIN_CLAVE:admin12345}
app.api.usuarios.semilla.operador.clave=${SEED_OPERADOR_CLAVE:operador123}
app.api.usuarios.semilla.visor.clave=${SEED_VISOR_CLAVE:visor12345}
app.api.usuarios.semilla.actualizar-claves-si-existe=${SEED_ACTUALIZAR_CLAVES_SI_EXISTE:true}

